services:
  books_backend_service:
    image: books_image
    container_name: "books_backend_container"
    networks:
      - books_network
    environment:
      DB_HOST: books_db_container
      DB_PORT: 5432
      DB_USER: main_user
      DB_PASS: main_user1234
      DB_NAME: book_db
    depends_on:
      books_db_service:
        condition: service_healthy

  books_db_service:
    image: postgres:17
    container_name: "books_db_container"
    environment:
      POSTGRES_USER: main_user
      POSTGRES_PASSWORD: main_user1234
      POSTGRES_DB: book_db
    ports:
      - "6432:5432"
    networks:
      - books_network
    volumes:
      - books_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U main_user -d book_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  books_nginx_service:
    image: nginx
    container_name: "books_nginx_container"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - books_network
    depends_on:
      - books_backend_service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost" ]
      interval: 30s
      timeout: 5s
      retries: 3

networks:
  books_network:
    driver: bridge

volumes:
  books_data:
