services:
  books_backend_service:
    image: books_image
    container_name: "books_backend_container"
    ports:
      - "7777:8000"
    build:
      context: .
    networks:
      - books_network
    env_file:
      - .env
    depends_on:
      - books_db_service


  books_db_service:
    image: postgres:17
    container_name: "books_db_container"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "6432:5432"
    networks:
      - books_network
    volumes:
      - books_data:/var/lib/postgresql/data

  books_nginx:
    image: nginx
    container_name: "books_nginx"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - books_network

networks:
  books_network:
    external: true

volumes:
  books_data:
