services:
  books_backend_service:
    image: books_image
    container_name: "books_backend_container"
    ports:
      - "7777:8000"
    build:
      context: .
    networks:
      - books_network
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-books_db_container}
      DB_PORT: ${DB_PORT:-5432}
      DB_USER: ${DB_USER:-main_user}
      DB_PASS: ${DB_PASS:-main_user1234}
      DB_NAME: ${DB_NAME:-book_db}
    depends_on:
      - books_db_service

  books_db_service:
    image: postgres:17
    container_name: "books_db_container"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER:-main_user}
      POSTGRES_PASSWORD: ${DB_PASS:-main_user1234}
      POSTGRES_DB: ${DB_NAME:-book_db}
    ports:
      - "6432:5432"
    networks:
      - books_network
    volumes:
      - books_data:/var/lib/postgresql/data

  books_nginx_service:
    image: nginx
    container_name: "books_nginx_container"
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - books_network
    depends_on:
      - books_backend_service

networks:
  books_network:
    external: true

volumes:
  books_data:
