"""add in field date_of_writing nullable

Revision ID: 3cc3ba7ab7c3
Revises: 1ac6030bfb00
Create Date: 2025-08-17 00:29:12.539335

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "3cc3ba7ab7c3"
down_revision: Union[str, Sequence[str], None] = "1ac6030bfb00"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "date_of_writing", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "book", "date_of_writing", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
